class DifferenceModel:
    RelCO = []
    AbsCO = []
    RelNO = []
    AbsNO = []
    RelNO2 = []
    AbsNO2 = []
    RelO3NO2 = []
    AbsO3NO2 = []
    RelPressure = []
    RelTemperature = []
    RelHumidity = []
    AbsPressure = []
    AbsTemperature = []
    AbsHumidity = []
    Date_Time = []
