class Omegas:
    CO_X = []
    NO_X = []
    NO2_X = []
    O3NO2_X = []
    O3_X = []
    Pressure_X = []
    Temperature_X = []
    Humidity_X = []
    CO_Y = []
    NO_Y = []
    NO2_Y = []
    O3NO2_Y = []
    O3_Y = []
    Pressure_Y = []
    Temperature_Y = []
    Humidity_Y = []
    CO_S = []
    NO_S = []
    NO2_S = []
    O3_S = []
    O3NO2_S = []
    Intervals = []

